spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost/orders
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      group-id: order-service-group
    bootstrap-servers: localhost:9092
server:
  port: 8080

